title: <p align="center"> Chaya lakshmi </p>
logo: /assets/img/chaya.jpg
description:
  <p align="center">
  <a href="assets/img/ChayaLakshmiParuchuri_Data_Engineer.pdf">Resume</a> |
  <a href="https://github.com/chaydc999">GitHub</a>
  
  <br>   
  Experienced in Big data technnologies like spark,hive,pig,
  hbase and oozie.
  Experienced in python programming
  <br>
  </p>

theme: jekyll-theme-minimal
